x-app-dev: &app-dev
    image: openfoodfacts/openfoodfacts-exports:dev
    build:
      context: .
      target: runtime-dev
      args:
        OFF_UID: ${OFF_UID:-1000}
        OFF_GID: ${OFF_GID:-1000}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.12}
    volumes:
      # make updates to code available
      - ./openfoodfacts_exports:/app/openfoodfacts_exports
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      # make tests available
      - ./.cov:/app/.cov

services:
  scheduler:
    <<: *app-dev
  workers:
    <<: *app-dev